[package]
name = "TaoHe"
version = "0.0.1"
authors = ["Ville Sundell / Solarius Intellectual Properties Ky"]
license = "Apache-2.0"

[addresses]
TaoHe = "0x2f66c09143acc52a85fec529a4e20c85"

[dependencies.Connector]
git = "https://github.com/taoheorg/connector-dummy.git"
addr_subst = { "std" = "0x1" }
rev = "2125806ade4a1b0995c370524e69c7c3a864724e"

[dependencies.MoveStdlib]
git = "https://github.com/move-language/move.git"
rev = "b53bb030b556a4e6ac2728d50ec7baaddf0b9a56"
subdir = "language/move-stdlib"
addr_subst = { "std" = "0x1" }
