[package]
name = "TaoHe"
version = "0.0.1"
authors = ["Ville Sundell / Solarius Intellectual Properties Ky"]
license = "Apache-2.0"

[addresses]
TaoHe = "0x2f66c09143acc52a85fec529a4e20c85"
Connector = "0x2f66c09143acc52a85fec529a4e20c85"
Std = "0x1"

[dependencies.Connector]
git = "https://github.com/taoheorg/connector-dummy.git"
rev = "ad6581bc051f33517173a411ee6ef0846d16600c"

[dependencies.MoveStdlib]
git = "https://github.com/move-language/move.git"
rev = "e2bb7e9822a6c15154149599f3c44f34258b72c0"
subdir = "language/move-stdlib"
addr_subst = { "std" = "0x1" }
