[package]
name = "TaoHe"
version = "0.0.1"
authors = ["Ville Sundell / Solarius Intellectual Properties Ky"]
license = "Apache-2.0"

[addresses]
TaoHe = "0x2f66c09143acc52a85fec529a4e20c85"
Connector = "0x2f66c09143acc52a85fec529a4e20c85"
Std = "0x1"

[dependencies.Connector]
git = "https://github.com/taoheorg/connector-dummy.git"
rev = "ad6581bc051f33517173a411ee6ef0846d16600c"

[dependencies.MoveStdlib]
git = "https://github.com/move-language/move.git"
rev = "d253bf1c21314679d17e6935116f30baf409f264"
subdir = "language/move-stdlib"
